name: build_and_test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  release:
    types: [created]
jobs:
  test:
    name: nDPI on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "ubuntu-18.04", "macOS-latest", "macos-11"]

    steps:
    - uses: actions/checkout@v2
    - name: Install Ubuntu Prerequisites
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install autoconf automake libtool pkg-config gettext libjson-c-dev flex bison libpcap-dev libgcrypt20-dev
    - name: Installing MacOS prerequisites
      if: startsWith(matrix.os, 'macOS')
      run: |
        brew install autoconf automake libtool pkg-config gettext json-c libgcrypt
    - name: Build nDPI
      run: |
        git clone --branch dev https://github.com/ntop/nDPI.git
        cd nDPI
        env CFLAGS='-Werror' ./autogen.sh
        make all
    - name: Test nDPI
      run: |
        cd tests
        ./do.sh
        ./do-unit.sh
        ./do-dga.sh
    
